### ISSUE TITLE
Conflict with markdown-preview-plus package

### ISSUE THREAD

**Issue by aswolf** [lexicalunit/language-atom-notes#3]
I am a user of atom-notes together with markdown-preview-plus. This combination gives me the ability to view compiled math equations (which are not available in the markdown-preview package).

Unfortunately, language-atom-notes prevents markdown-preview-plus from showing any previews of the markdown files. All functioning stops as soon as language-atom-notes is activated. Otherwise, it has no problems with atom-notes. It would be great to get the highlighting of links provided by this package!

Thanks!

**Comment by lexicalunit** [comment]
Thankfully, @aswolf, `markdown-preview-plus` supports a `grammars` configuration. If you go into the settings for `language-atom-notes` and add to the list of packages for the setting `Interoperate with these packages` then I believe that will resolve your issue. I'm going to test this out myself and if it works, I'll add `markdown-preview-plus` to the default list of interop packages.

**Comment by lexicalunit** [comment]
@aswolf I just fixed a bug with the interop setting and added `markdown-preview-plus` to the default list of supported packages. Please give v0.4.0 a try!

**Comment by aswolf** [comment]
Thanks, this resolved the issue!
