### ISSUE TITLE
Grammar seems to conflict with dot files

### ISSUE THREAD

**Issue by jkamenik** [lexicalunit/language-atom-notes#4]
I use atom-notes for almost all my not taking.  I added ".dot" my Extensions list so that it could find and open graphviz files.  But now the graphviz files when opened have the "Atom Note" grammar instead of the "Graphviz" grammar.  I am not sure how to fix this.

**Comment by lexicalunit** [comment]
@jkamenik you can use `atom-notes` without having to install `language-atom-notes` which would work, but then you'd lose syntax highlighting for interlinks as well as interoperability with `markdown-preview` and `spell-check`.

I'm going to add an configuration option to `language-atom-notes` to help resolve this issue for you. Hopefully I should have something for you in the next few minutes.

**Comment by lexicalunit** [comment]
ok @jkamenik, give v0.3.0 a try 🤞
